### ISSUE TITLE
Feature: Highlights Design System Improvements

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1176]
### Type of feature

🍕 Feature

### Current behavior

During a Design Exploration we did - [[Figma](https://www.figma.com/file/KwtbAJzP2Y8zENhVsKplRo/OpenSauced?type=design&node-id=0%3A1&t=hCipvyDYRn54dz4z-1)]

1. New types of Highlights will need a type added 
2. Repo tag should be added to the highlight [isse, pr, and blog post]
3. Milestone highlights

## New design
- type on the top left
- Repo tag bottom right
- Quick share to twitter icon top right

<img width="405" alt="Screen Shot 2023-05-13 at 1 15 52 AM" src="https://github.com/open-sauced/insights/assets/5713670/4fff0271-47de-4aa3-9c44-2d7213fbdbc5">

## Milestones
- one with post (PR)
- one without post

<img width="405" alt="Screen Shot 2023-05-13 at 1 15 32 AM" src="https://github.com/open-sauced/insights/assets/5713670/18176aeb-2b4e-405f-af37-e3b8d15986d7">

### Additional context

We will need to update the logic for highlights to include the check for type of highlight. For now treat everything as a pull request highlight when shipping live.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
Should the link in the description be a figma link or a dropbox one?

**Comment by bdougie** [comment]
> Should the link in the description be a figma link or a dropbox one? 

Should be Figma. Just updated.

**Comment by a0m0rajab** [comment]
Thank you for that.

**Comment by bdougie** [comment]
@OgDev-01 this never got started but the small improvements to the Highlights will be needed prior to the 24th.

- [ ] repo name on card 
- [ ] highlight type added to the card, "pull request"

We can add API updates to include new highlight types separately
