### ISSUE TITLE
Feature: Sign Up Roadblocks - Tracking Issue

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1180]
### Type of feature

🍕 Feature

### Current behavior

There are a lot of places we should encourage sign in

### Suggested solution

- [ ] Force login when someone paginates any data on repository or contributors tab
- [ ] Replace the reports page login button (it's been removed). 
- [ ] Hide all insights except contributors on the dashboard - https://github.com/open-sauced/insights/issues/722

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by chhristopher** [comment]
Points of interest to force login:
- Adding any filters (ie top 100 repos, most spammed, etc)
- Under Repositories, wondering if it is possible to show the first 5 repos in the chart below and blur the rest- forcing folks to 
login to view the repos

**Comment by takanome-dev** [comment]
We should also force login when creating an insight page

![force-login](https://github.com/open-sauced/insights/assets/79809121/7215f1ac-51e6-4d56-a1d9-127a8c8feaf1)

**Comment by brandonroberts** [comment]
@takanome-dev you shouldn't be on this page if you're not logged in. We have a bug that doesn't redirect you somewhere else on logout currently

**Comment by takanome-dev** [comment]
Ah that's why. Hum, I will look into it 👍
