### ISSUE TITLE
[Tracking] Reports Page v1

### ISSUE THREAD

**Issue by pixelsbyeryc** [open-sauced/insights#165]
## Summary

We need to have reports ready for the hacktoberfest event. 

A lot of conversation around a **more complete** version of the Reports page happened on #93, but for now, we'll stick to an MVP-version, providing only the CSV, and scoping a PDF Report.

[🔗 **View Designs in Figma**](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=1379%3A2075)

We'll have two versions, for each persona:
1. **For Digital Ocean** (during the Hacktoberfest event)
2. **For the Insiders** group

### Design Tasks:
- [ ] #92 
- [ ] #153 
- [ ] #154 

### Development Tasks:
- **Hacktoberfest `top priority`**
  - [x] #166 
  - [x] #167 
  - [x] #168 
  - [x] #169 
- **Insiders** `after the hacktoberfest is released`
  - [ ] [Front-End] Create the `SidebarContents` component
  - [ ] [Front-End] Create a `Search` input component
  - [ ] [Front-End] Create a Repository Card component for reports search results
  - [ ] [Front-End] Create the `ReportSummary` component
  - [ ] [Front-End] Implement the Insider Reports Page
  - [ ] Create the logic for generating the Insider reports

---

### Hacktobefest Version

- Can only filter (by the pre-defined opinionated filters we have)
- History will show below

<img width="1440" alt="Reports v1 - Digital Ocean@2x" src="https://user-images.githubusercontent.com/101464991/183985405-9bf0b4c2-895c-4269-bdf4-aa3c79ad7ea4.png">

### Insiders Version

- Cannot use the pre-defined opinionated filters (because it would grab too many repos)
- User has to select which repos they want reports from
- History will be shown in another page (user can navigate through the left sidebar)

<img width="1440" alt="Reports v1 - Insiders - Your Reports@2x" src="https://user-images.githubusercontent.com/101464991/183985403-567b331a-ed0b-45f8-af7b-51fa43a8ae3d.png">
<img width="1440" alt="Reports v1 - Insiders - Generate Reports@2x" src="https://user-images.githubusercontent.com/101464991/183985409-bc023b4a-4bb2-4f2d-bbf1-fe4605fa8574.png">
