### ISSUE TITLE
Tracking Issue: Insight Hub (Custom Repo Dashboards)

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#393]
## Summary

This feature will give users the option to create their own Dashboards with selected repositories.

### Design
- [x] #397
- [x] #398
- [ ] Create team association to custom repo dashboards

### Front-End
- [x] #499
- [x] #508
- [x] #509
- [x] #510
- [x] #511
- [x] #512

### Backend
- [ ] Create custom insight pages with owners (public switch)
- [ ] Implement roles and permissions
- [ ] SSR?

### Document
- [x] #513
