### ISSUE TITLE
tracking: Improve the data and UI

### ISSUE THREAD

**Issue by pixelsbyeryc** [open-sauced/insights#445]
## Summary

There are still some pieces we need to adjust so the app displays consistent data, and has a great flow.

The changes will affect **Repositories** tab, and **Contributors** tab.

### Global
- [x] #446
- [x] #158 

### Repositories
- [ ] #418 
- [x] #447
- [x] #448
- [ ] feature: Add Pagination numbers
- [x] #449
- [x] https://github.com/open-sauced/insights/issues/457

### Contributors
- [ ] feature: Add Pagination
- [x] #450
- [ ] feature: Add tooltips to the contribution chart to show some info (number of contributions)
