### ISSUE TITLE
Tracking: Sync emails to contributors

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#545]
- [ ] Create ETL script
- [ ] In DB create additional tables for email contributors and GitHub users
- [ ] Update frontend to reflect the syncing
- [x] https://github.com/open-sauced/insights/issues/541
